### ISSUE TITLE
environmental problems

### ISSUE THREAD

**Issue by qqer123456** [floriangroetschla/CoRe-GD#1]
When installing graph coating, the Python version needs to be below 3.7, while installing torch=2.0.0 requires Python 3.8 or above

**Comment by floriangroetschla** [comment]
I just followed the instructions in the README, except for a small typo I just fixed, the package seemed to install fine. Did you use the following graph coarsening repo: https://github.com/SergeiShumilin/graph-coarsening-up-to-date ?
If so, can you provide more details on what is going wrong?

**Comment by qqer123456** [comment]
I am installing graph coating and the error that occurred is shown in the picture
![微信图片_20240515130745](https://github.com/floriangroetschla/CoRe-GD/assets/169814742/e58a4c68-2d25-498f-b581-ccc58a306b09)

**Comment by qqer123456** [comment]
Thank you for your reply. I have already resolved the issue

**Comment by floriangroetschla** [comment]
Okay, I will mark this issue as completed then. Feel free to reach out if there are any other problems with the installation.
